"""Add OTP verification fields

Revision ID: 9a1a62862c83
Revises: e4f6b87e8778
Create Date: 2026-08-06 13:00:19.679313+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a1a62862c83'
down_revision: Union[str, None] = 'e4f6b87e8778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('otp_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_code')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
